
services:
  postgres-api-lost:
    image: postgres:17
    hostname: postgres-api-lost
    ports:
      - "9999:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbLost
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

  minio-api:
    hostname: minio-api-lost
    image: 'minio/minio:latest'
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data-lost:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  pgadmin-api-lost:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-api-lost


volumes:
  db-data:
  minio-data-lost:
    driver: local