# Generated by Django 5.1.1 on 2025-06-04 20:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('name', models.CharField(db_column='tx_name')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('title', models.CharField(db_column='tx_title', max_length=100)),
                ('description', models.TextField(db_column='tx_description', max_length=250)),
                ('date_found', models.DateTimeField(db_column='dt_found')),
                ('is_resolved', models.BooleanField(db_column='cs_resolved', default=False)),
                ('city', models.CharField(db_column='tx_city', default='brasil', max_length=100)),
                ('category', models.ForeignKey(db_column='id_category', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('user', models.ForeignKey(db_column='id_user', default='1', on_delete=django.db.models.deletion.CASCADE, related_name='item_found', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_found',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('title', models.CharField(db_column='tx_title', max_length=100)),
                ('last_seen_details', models.TextField(db_column='tx_description', max_length=250)),
                ('reward', models.FloatField(db_column='nb_price')),
                ('date_lost', models.DateTimeField(db_column='dt_lost')),
                ('is_resolved', models.BooleanField(db_column='cs_resolved', default=False)),
                ('city', models.CharField(db_column='tx_city', default='brasil', max_length=100)),
                ('category', models.ForeignKey(db_column='id_category', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('user', models.ForeignKey(db_column='id_user', default='1', on_delete=django.db.models.deletion.CASCADE, related_name='item_lost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_lost',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileImageItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('filename', models.CharField(db_column='tx_file_name', max_length=255)),
                ('remote_name', models.CharField(db_column='tx_remote_name', max_length=1024)),
                ('found_item', models.ForeignKey(blank=True, db_column='id_found_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_image_items', to='core.founditem')),
                ('lost_item', models.ForeignKey(blank=True, db_column='id_lost_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_image_items', to='core.lostitem')),
            ],
            options={
                'db_table': 'file_image_item',
                'managed': True,
            },
        ),
    ]
