# Generated by Django 5.1.1 on 2025-06-16 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('date_modified', models.DateTimeField(auto_now=True, db_column='dt_modified')),
                ('text', models.TextField(db_column='tx_text', max_length=500)),
                ('comment', models.ForeignKey(blank=True, db_column='id_comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.comment')),
                ('found_item', models.ForeignKey(blank=True, db_column='id_found_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.founditem')),
                ('lost_item', models.ForeignKey(blank=True, db_column='id_lost_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.lostitem')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
